module languages.web.javascript.bundlers.vite;

import std.process : execute, Config;
import std.path;
import std.file;
import std.algorithm;
import std.array;
import std.string : strip, indexOf;
import languages.web.javascript.bundlers.base;
import infrastructure.config.schema.schema;
import infrastructure.utils.files.hash;
import infrastructure.utils.logging;

/// Framework detection for Vite plugins
private enum Framework { None, React, Vue, Svelte, Preact }

/// Vite bundler - modern dev server with lightning-fast HMR and optimized production builds
class ViteBundler : Bundler
{
    BundleResult bundle(const(string[]) sources, JSConfig config, in Target target, in WorkspaceConfig workspace)
    {
        BundleResult result;
        
        if (!isAvailable())
        {
            result.error = "vite not found. Install: npm install -g vite";
            return result;
        }
        
        if (!config.configFile.empty && exists(config.configFile))
            return bundleWithConfigFile(config.configFile, workspace, result);
        
        string autoConfig = detectViteConfig(sources);
        if (!autoConfig.empty)
        {
            structuredLog.debug_("detected_vite_config").field("detail", autoConfig).emit();
            return bundleWithConfigFile(autoConfig, workspace, result);
        }
        
        return bundleWithGeneratedConfig(sources, config, target, workspace, result);
    }
    
    private BundleResult bundleWithConfigFile(string configFile, in WorkspaceConfig workspace, BundleResult result)
    {
        structuredLog.debug_("using_vite_config").field("detail", configFile).emit();
        
        string configDir = dirName(absolutePath(configFile));
        auto res = execute(["npx", "vite", "build", "--config", configFile], null, Config.none, size_t.max, configDir);
        
        if (res.status != 0)
        {
            result.error = "vite build failed: " ~ res.output;
            return result;
        }
        
        result.success = true;
        string outputDir = buildPath(configDir, "dist");
        if (!exists(outputDir)) outputDir = workspace.options.outputDir;
        collectOutputs(outputDir, result);
        
        if (result.outputs.empty)
        {
            result.error = "No outputs generated by Vite";
            return result;
        }
        
        result.outputHash = FastHash.hashFiles(result.outputs);
        return result;
    }
    
    private BundleResult bundleWithGeneratedConfig(const(string[]) sources, JSConfig config, in Target target, in WorkspaceConfig workspace, BundleResult result)
    {
        string entry = config.entry.empty ? sources[0] : config.entry;
        string outputDir = workspace.options.outputDir;
        mkdirRecurse(outputDir);
        string outputFile = target.name.split(":")[$ - 1] ~ ".js";
        
        Framework framework = detectFramework(sources);
        string viteConfig = generateConfig(entry, outputDir, outputFile, config, framework);
        
        string projectDir = findProjectDir(entry);
        string tempConfig = buildPath(projectDir, "vite.config.temp.cjs");
        std.file.write(tempConfig, viteConfig);
        scope(exit) if (exists(tempConfig)) remove(tempConfig);
        
        structuredLog.debug_("generated_vite_config").field("detail", tempConfig).emit();
        
        auto res = execute(["npx", "vite", "build", "--config", tempConfig], null, Config.none, size_t.max, projectDir);
        
        if (res.status != 0)
        {
            result.error = "vite build failed: " ~ res.output;
            return result;
        }
        
        result.success = true;
        collectOutputs(outputDir, result);
        if (result.outputs.empty)
        {
            string primaryOutput = buildPath(outputDir, outputFile);
            if (exists(primaryOutput)) result.outputs = [primaryOutput];
        }
        result.outputHash = FastHash.hashFiles(result.outputs);
        return result;
    }
    
    private string detectViteConfig(const(string[]) sources)
    {
        if (sources.empty) return "";
        string dir = dirName(sources[0]);
        foreach (cfg; ["vite.config.ts", "vite.config.js", "vite.config.mjs"])
        {
            string path = buildPath(dir, cfg);
            if (exists(path)) return path;
        }
        return "";
    }
    
    private Framework detectFramework(const(string[]) sources)
    {
        if (sources.any!(s => s.endsWith(".vue"))) return Framework.Vue;
        if (sources.any!(s => s.endsWith(".svelte"))) return Framework.Svelte;
        if (sources.any!(s => s.endsWith(".jsx") || s.endsWith(".tsx")))
        {
            string pkg = findPackageJson(sources);
            if (!pkg.empty && exists(pkg))
            {
                try
                {
                    auto content = readText(pkg);
                    if (content.indexOf("\"react\"") != -1) return Framework.React;
                    if (content.indexOf("\"preact\"") != -1) return Framework.Preact;
                }
                catch (Exception) {}
            }
            return Framework.React;
        }
        return Framework.None;
    }
    
    private string findPackageJson(const(string[]) sources)
    {
        if (sources.empty) return "";
        string dir = dirName(sources[0]);
        while (dir != "/" && dir.length > 1)
        {
            string pkg = buildPath(dir, "package.json");
            if (exists(pkg)) return pkg;
            dir = dirName(dir);
        }
        return "";
    }
    
    private string findProjectDir(string entry)
    {
        string dir = dirName(absolutePath(entry));
        while (dir != "/" && dir.length > 1)
        {
            if (exists(buildPath(dir, "package.json"))) return dir;
            dir = dirName(dir);
        }
        return dirName(absolutePath(entry));
    }
    
    private string generateConfig(string entry, string outputDir, string outputFile, JSConfig config, Framework framework)
    {
        string pluginsList = getPluginsList(framework);
        string libSection = config.mode == JSBuildMode.Library ? `
    lib: {
      entry: '` ~ absolutePath(entry) ~ `',
      name: '` ~ baseName(outputFile, ".js") ~ `',
      formats: ['` ~ formatToVite(config.format) ~ `'],
      fileName: (format) => '` ~ baseName(outputFile, ".js") ~ `.${format}.js'
    },` : "";
        
        string externals = config.external.empty ? "" : `
    rollupOptions: { external: [` ~ config.external.map!(e => "'" ~ e ~ "'").join(", ") ~ `] },`;
        
        return `const { createRequire } = require('module');
const { join } = require('path');
const projectRequire = createRequire(join(__dirname, 'package.json'));

module.exports = {
  plugins: [` ~ pluginsList ~ `],
  build: {
    outDir: '` ~ absolutePath(outputDir) ~ `',
    emptyOutDir: true,
    minify: ` ~ (config.minify ? "'esbuild'" : "false") ~ `,
    sourcemap: ` ~ (config.sourcemap ? "true" : "false") ~ `,` ~ libSection ~ externals ~ `
  },
  resolve: { extensions: ['.js', '.jsx', '.ts', '.tsx', '.json', '.vue', '.svelte'] },
  esbuild: { target: '` ~ config.target ~ `', jsx: ` ~ (config.jsx ? "'transform'" : "'automatic'") ~ `, jsxFactory: '` ~ config.jsxFactory ~ `' }
};`;
    }
    
    private string getPluginsList(Framework f)
    {
        final switch (f)
        {
            case Framework.None: return "";
            case Framework.React: return "projectRequire('@vitejs/plugin-react').default()";
            case Framework.Vue: return "projectRequire('@vitejs/plugin-vue').default()";
            case Framework.Svelte: return "projectRequire('@sveltejs/vite-plugin-svelte').svelte()";
            case Framework.Preact: return "projectRequire('@preact/preset-vite').default()";
        }
    }
    
    private string formatToVite(OutputFormat f)
    {
        final switch (f)
        {
            case OutputFormat.ESM: return "es";
            case OutputFormat.CommonJS: return "cjs";
            case OutputFormat.IIFE: return "iife";
            case OutputFormat.UMD: return "umd";
        }
    }
    
    private void collectOutputs(string outputDir, ref BundleResult result)
    {
        if (!exists(outputDir) || !isDir(outputDir)) return;
        foreach (entry; dirEntries(outputDir, SpanMode.depth))
        {
            if (entry.isFile)
            {
                string ext = extension(entry.name);
                if (ext == ".js" || ext == ".mjs" || ext == ".cjs" || ext == ".css" || ext == ".map")
                    result.outputs ~= entry.name;
            }
        }
    }
    
    bool isAvailable() { return execute(["npx", "vite", "--version"]).status == 0; }
    string name() const => "vite";
    string getVersion()
    {
        auto r = execute(["npx", "vite", "--version"]);
        return r.status == 0 ? r.output.strip : "unknown";
    }
}
