module languages.compiled.cpp.core.handler;

import std.stdio;
import std.process;
import std.file;
import std.path;
import std.algorithm;
import std.array;
import std.json;
import std.conv;
import languages.compiled.base;
import languages.compiled.cpp.core.config;
import infrastructure.toolchain;
import languages.compiled.cpp.analysis.analysis;
import languages.compiled.cpp.tooling.tools;
import languages.compiled.cpp.builders;
import infrastructure.config.schema.schema;
import infrastructure.analysis.targets.types;
import infrastructure.utils.files.hash;
import infrastructure.utils.logging;
import engine.caching.actions.action : ActionCache, ActionCacheConfig, ActionId, ActionType;

/// Generate PCH header file from suggested headers
private string generatePchHeader(string[] headers, string outputDir) @system
{
    if (!exists(outputDir))
        mkdirRecurse(outputDir);
    
    string pchPath = buildPath(outputDir, "builder_pch.h");
    
    string content = "// Auto-generated PCH header\n// Generated by Builder\n\n";
    foreach (header; headers)
    {
        if (header.canFind("/") || header.canFind("\\"))
            content ~= "#include \"" ~ header ~ "\"\n";
        else
            content ~= "#include <" ~ header ~ ">\n";
    }
    
    std.file.write(pchPath, content);
    structuredLog.debug_("generated_pch_header_").field("detail", "Generated PCH: " ~ pchPath).emit();
    
    return pchPath;
}

/// C++ build handler with comprehensive feature support
class CppHandler : BaseCompiledLanguageHandler
{
    private CppConfig _config;
    
    this() { super(null); }
    
    // ===== Required Overrides =====
    
    override protected string languageId() const pure nothrow => "cpp";
    
    override protected TargetLanguage languageType() const pure nothrow => TargetLanguage.Cpp;
    
    override protected string[] configKeys() const pure nothrow => ["cpp", "cppConfig", "c++"];
    
    override protected string toolchainNotFoundError() const pure nothrow =>
        "C++ compiler not available. Install GCC, Clang, or MSVC.";
    
    override protected string detectToolchain(in Target target, in WorkspaceConfig config) @system
    {
        _config = parseCppConfig(target);
        enhanceConfigFromProject(_config, target, config);
        
        import infrastructure.toolchain.detection.detector : ExecutableDetector;
        
        // Auto-detect compiler
        final switch (_config.compiler)
        {
            case Compiler.Auto:
                auto clang = ExecutableDetector.findInPath("clang++");
                if (!clang.empty) return clang;
                auto gcc = ExecutableDetector.findInPath("g++");
                if (!gcc.empty) return gcc;
                version(Windows)
                {
                    auto msvc = ExecutableDetector.findInPath("cl");
                    if (!msvc.empty) return msvc;
                }
                return "";
            case Compiler.Clang:
                return ExecutableDetector.findInPath("clang++");
            case Compiler.GCC:
                return ExecutableDetector.findInPath("g++");
            case Compiler.MSVC:
                return ExecutableDetector.findInPath("cl");
            case Compiler.Intel:
                return ExecutableDetector.findInPath("icpc");
            case Compiler.Custom:
                return _config.customCompiler.empty ? "" : (_config.customCompiler.exists ? _config.customCompiler : "");
        }
    }
    
    // ===== Build Methods =====
    
    override protected LanguageBuildResult buildExecutable(in Target target, in WorkspaceConfig config, string toolPath) @system
    {
        _config.outputType = OutputType.Executable;
        
        auto buildResult = compileTarget(target, config);
        return toBuildResult(buildResult);
    }
    
    override protected LanguageBuildResult buildLibrary(in Target target, in WorkspaceConfig config, string toolPath) @system
    {
        // Check if header-only library
        bool isHeaderOnly = target.sources.all!(s => 
            s.endsWith(".h") || s.endsWith(".hpp") || s.endsWith(".hxx")
        );
        
        if (isHeaderOnly || _config.outputType == OutputType.HeaderOnly)
        {
            structuredLog.info("headeronly_library_detected").emit();
            LanguageBuildResult result;
            result.success = true;
            result.outputs = target.sources.dup;
            result.outputHash = FastHash.hashStrings(target.sources.dup);
            return result;
        }
        
        if (_config.outputType == OutputType.Executable)
            _config.outputType = OutputType.StaticLib;
        
        auto buildResult = compileTarget(target, config);
        return toBuildResult(buildResult);
    }
    
    override protected LanguageBuildResult buildAndRunTests(in Target target, in WorkspaceConfig config, string toolPath) @system
    {
        _config.outputType = OutputType.Executable;
        
        auto buildResult = compileTarget(target, config);
        if (!buildResult.success)
            return toBuildResult(buildResult);
        
        // Run the test executable
        if (!buildResult.outputs.empty)
        {
            string testExe = buildResult.outputs[0];
            structuredLog.info("running_tests_").field("detail", "Running tests: " ~ testExe).emit();
            
            auto res = execute([testExe]);
            if (res.status != 0)
                return errorResult("Tests failed: " ~ res.output);
            
            structuredLog.info("tests_passed").emit();
        }
        
        LanguageBuildResult result;
        result.success = true;
        result.outputHash = buildResult.outputHash;
        return result;
    }
    
    override protected LanguageBuildResult buildCustom(in Target target, in WorkspaceConfig config, string toolPath) @system
    {
        LanguageBuildResult result;
        result.success = true;
        result.outputHash = FastHash.hashStrings(target.sources.dup);
        return result;
    }
    
    // ===== Tooling =====
    
    override protected bool shouldFormat(in Target target) const @system => _config.format;
    override protected bool shouldLint(in Target target) const @system => _config.analyzer != StaticAnalyzer.None;
    
    override protected CompiledLanguageResult runFormatter(in Target target, in WorkspaceConfig config) @system
    {
        CompiledLanguageResult result;
        result.success = true;
        
        if (!ClangFormat.isAvailable())
        {
            structuredLog.warning("clangformat_not_available_skipping").emit();
            return result;
        }
        
        ClangFormat.format(target.sources.dup, _config.formatStyle, true);
        return result;
    }
    
    override protected CompiledLanguageResult runLinter(in Target target, in WorkspaceConfig config) @system
    {
        CompiledLanguageResult result;
        result.success = true;
        
        auto analysisResult = runStaticAnalysis(target);
        if (analysisResult.hadIssues)
        {
            result.hadLintIssues = true;
            result.lintIssues = analysisResult.issues;
        }
        
        return result;
    }
    
    override protected string getOutputName(string name, TargetType type) const pure nothrow
    {
        string ext = "";
        string prefix = "";
        
        final switch (_config.outputType)
        {
            case OutputType.Executable:
                version(Windows) ext = ".exe";
                break;
            case OutputType.SharedLib:
                version(Windows) ext = ".dll";
                else version(OSX) ext = ".dylib";
                else ext = ".so";
                break;
            case OutputType.StaticLib:
                version(Windows) { prefix = ""; ext = ".lib"; }
                else { prefix = "lib"; ext = ".a"; }
                break;
            case OutputType.Object:
                ext = ".o";
                break;
            case OutputType.HeaderOnly:
                break;
        }
        
        return prefix ~ name ~ ext;
    }
    
    // ===== Private Implementation =====
    
    private LanguageBuildResult toBuildResult(CppCompileResult compileResult) pure nothrow
    {
        LanguageBuildResult result;
        result.success = compileResult.success;
        result.error = compileResult.error;
        result.outputs = compileResult.outputs;
        result.outputHash = compileResult.outputHash;
        return result;
    }
    
    private CppCompileResult compileTarget(in Target target, in WorkspaceConfig config) @system
    {
        auto builder = CppBuilderFactory.create(_config, actionCache);
        
        if (!builder.isAvailable())
        {
            CppCompileResult result;
            result.error = "C++ builder '" ~ builder.name() ~ "' not available. Install GCC, Clang, or MSVC.";
            return result;
        }
        
        structuredLog.debug_("using_cpp_builder_").field("detail", "Using C++ builder: " ~ builder.name() ~ " (" ~ builder.getVersion() ~ ")").emit();
        
        // Optimize with precompiled headers if beneficial
        if (_config.pch.strategy == PchStrategy.Auto && target.sources.length > 5)
        {
            auto pchHeaders = PchOptimizer.suggestPchHeaders(target.sources.dup, _config.includeDirs);
            if (!pchHeaders.empty)
            {
                double benefit = PchOptimizer.estimatePchBenefit(target.sources.dup, pchHeaders);
                if (benefit > 30.0)
                {
                    structuredLog.info("pch_benefit_").field("detail", "PCH would benefit ~" ~ benefit.to!string[0 .. min(5, $)] ~ "% of includes").emit();
                    
                    CppConfig pchConfig = _config;
                    pchConfig.pch.strategy = PchStrategy.Manual;
                    pchConfig.pch.header = generatePchHeader(pchHeaders, config.options.outputDir);
                    pchConfig.pch.output = buildPath(config.options.outputDir, "pch.h.gch");
                    
                    structuredLog.info("using_pch_").field("detail", "Using PCH with " ~ pchHeaders.length.to!string ~ " headers").emit();
                    
                    auto pchBuilder = CppBuilderFactory.create(pchConfig, actionCache);
                    return pchBuilder.build(target.sources, pchConfig, target, config);
                }
            }
        }
        
        auto compileResult = builder.build(target.sources, _config, target, config);
        
        if (compileResult.success && compileResult.hadWarnings && !compileResult.warnings.empty)
            reportWarnings(compileResult.warnings);
        
        return compileResult;
    }
    
    private CppConfig parseCppConfig(in Target target) @system
    {
        CppConfig config;
        
        auto json = parseTargetConfig(target);
        if (json != JSONValue.init)
        {
            try { config = CppConfig.fromJSON(json); }
            catch (Exception e)
                structuredLog.warning("failed_to_parse_cpp_config_").field("detail", "Using defaults: " ~ e.msg).emit();
        }
        
        // Apply target flags
        if (!target.flags.empty)
            config.compilerFlags ~= target.flags.dup;
        
        return config;
    }
    
    private void enhanceConfigFromProject(ref CppConfig config, in Target target, in WorkspaceConfig workspace) @system
    {
        if (target.sources.empty)
            return;
        
        string sourceDir = dirName(target.sources[0]);
        
        // Auto-detect build system
        if (config.buildSystem == BuildSystem.Auto)
        {
            config.buildSystem = detectBuildSystemImpl(sourceDir, workspace.root);
            if (config.buildSystem != BuildSystem.None)
                structuredLog.info("detected_build_system_").field("detail", "Detected: " ~ config.buildSystem.to!string).emit();
        }
        
        // Auto-detect entry point
        if (config.entry.empty && !target.sources.empty)
        {
            foreach (source; target.sources)
            {
                string basename = baseName(source, extension(source));
                if (basename == "main" || basename == "app")
                {
                    config.entry = source;
                    break;
                }
            }
            if (config.entry.empty)
                config.entry = target.sources[0];
        }
        
        // Add include directories from target
        if (!target.includes.empty)
            config.includeDirs ~= target.includes;
    }
    
    private BuildSystem detectBuildSystemImpl(string sourceDir, string projectRoot) @system
    {
        string[] searchDirs = [sourceDir, projectRoot];
        
        foreach (dir; searchDirs)
        {
            if (exists(buildPath(dir, "CMakeLists.txt")))
                return BuildSystem.CMake;
            if (exists(buildPath(dir, "meson.build")))
                return BuildSystem.Meson;
            if (exists(buildPath(dir, "BUILD")) || exists(buildPath(dir, "BUILD.bazel")))
                return BuildSystem.Bazel;
            if (exists(buildPath(dir, "xmake.lua")))
                return BuildSystem.Xmake;
            if (exists(buildPath(dir, "build.ninja")))
                return BuildSystem.Ninja;
            if (exists(buildPath(dir, "Makefile")) || exists(buildPath(dir, "makefile")))
                return BuildSystem.Make;
        }
        
        return BuildSystem.None;
    }
    
    private AnalysisResult runStaticAnalysis(in Target target) @system
    {
        final switch (_config.analyzer)
        {
            case StaticAnalyzer.None:
                return AnalysisResult();
            case StaticAnalyzer.ClangTidy:
                return ClangTidy.analyze(target.sources.dup, _config);
            case StaticAnalyzer.CppCheck:
                return CppCheck.analyze(target.sources.dup, _config);
            case StaticAnalyzer.PVSStudio:
            case StaticAnalyzer.Coverity:
                structuredLog.warning("analyzer_not_implemented_").field("detail", "Not implemented: " ~ _config.analyzer.to!string).emit();
                return AnalysisResult();
        }
    }
}

/// C handler (reuses CppHandler with C-specific settings)
class CHandler : CppHandler
{
    override protected string languageId() const pure nothrow => "c";
    override protected TargetLanguage languageType() const pure nothrow => TargetLanguage.C;
    override protected string[] configKeys() const pure nothrow => ["c", "cConfig"];
}
